import * as fs from "fs";
import * as path from "path";
import {
  defaultBrowserChannel,
  homeDir,
  hostPlatform,
  sanitizeJobName,
  schedulerLabel,
  shellQuotePosix,
  shellQuotePowerShell,
} from "./platform";
import { isFile, resolvePython, resolveSyncRoot, resolveTranscriptsDir } from "./paths";
import type { ZoomSyncSettings } from "./settings";
import { runProcess, type RunOptions, type RunResult } from "./runner";

const CRON_BEGIN = "# BEGIN zoom-mynotes-sync";
const CRON_END = "# END zoom-mynotes-sync";

export interface ScheduleContext {
  settings: ZoomSyncSettings;
  vaultPath: string;
  onLine?: RunOptions["onLine"];
}

/** Write portable env + runner scripts used by OS schedulers. */
export function writeLocalEnvFiles(
  settings: ZoomSyncSettings,
  vaultPath: string
): { envSh: string; envPs1: string; runSh: string; runPs1: string } {
  const root = resolveSyncRoot(settings);
  const out = resolveTranscriptsDir(settings, vaultPath);
  const py = resolvePython(settings);
  const channel = defaultBrowserChannel();
  const syncPy = path.join(root, "sync.py");

  const envSh = path.join(root, "local-env.sh");
  const envPs1 = path.join(root, "local-env.ps1");
  const runSh = path.join(root, "run-sync.sh");
  const runPs1 = path.join(root, "run-sync.ps1");

  const shBody =
    `# Generated by Zoom MyNotes Sync Obsidian plugin — do not commit secrets.\n` +
    `export ZOOM_TRANSCRIPTS_DIR=${shellQuotePosix(out)}\n` +
    `export ZOOM_HEADLESS=\${ZOOM_HEADLESS:-1}\n` +
    `export ZOOM_LOG_TITLES=\${ZOOM_LOG_TITLES:-0}\n` +
    `export ZOOM_BROWSER_CHANNEL=\${ZOOM_BROWSER_CHANNEL:-${channel}}\n` +
    `export PYTHONUNBUFFERED=1\n`;

  const psBody =
    `# Generated by Zoom MyNotes Sync Obsidian plugin — do not commit secrets.\n` +
    `$env:ZOOM_TRANSCRIPTS_DIR = ${shellQuotePowerShell(out)}\n` +
    `if (-not $env:ZOOM_HEADLESS) { $env:ZOOM_HEADLESS = '1' }\n` +
    `if (-not $env:ZOOM_LOG_TITLES) { $env:ZOOM_LOG_TITLES = '0' }\n` +
    `if (-not $env:ZOOM_BROWSER_CHANNEL) { $env:ZOOM_BROWSER_CHANNEL = '${channel}' }\n` +
    `$env:PYTHONUNBUFFERED = '1'\n`;

  const runShBody =
    `#!/usr/bin/env bash\n` +
    `set -euo pipefail\n` +
    `ROOT=${shellQuotePosix(root)}\n` +
    `cd "$ROOT"\n` +
    `# shellcheck disable=SC1091\n` +
    `source "$ROOT/local-env.sh"\n` +
    `exec ${shellQuotePosix(py)} ${shellQuotePosix(syncPy)}\n`;

  const runPsBody =
    `$ErrorActionPreference = 'Stop'\n` +
    `$Root = ${shellQuotePowerShell(root)}\n` +
    `Set-Location -LiteralPath $Root\n` +
    `. (Join-Path $Root 'local-env.ps1')\n` +
    `& ${shellQuotePowerShell(py)} ${shellQuotePowerShell(syncPy)}\n` +
    `exit $LASTEXITCODE\n`;

  fs.writeFileSync(envSh, shBody, "utf8");
  fs.writeFileSync(envPs1, psBody, "utf8");
  fs.writeFileSync(runSh, runShBody, { encoding: "utf8", mode: 0o755 });
  fs.writeFileSync(runPs1, runPsBody, "utf8");

  try {
    fs.chmodSync(runSh, 0o755);
    fs.chmodSync(envSh, 0o644);
  } catch {
    /* Windows may not support chmod the same way */
  }

  return { envSh, envPs1, runSh, runPs1 };
}

async function registerWindows(
  ctx: ScheduleContext,
  runPs1: string
): Promise<RunResult> {
  const root = resolveSyncRoot(ctx.settings);
  const script = path.join(root, "scripts", "register-task.ps1");
  const ps = process.env.SystemRoot
    ? path.join(
        process.env.SystemRoot,
        "System32",
        "WindowsPowerShell",
        "v1.0",
        "powershell.exe"
      )
    : "powershell.exe";

  if (isFile(script)) {
    return runProcess({
      kind: "register-task",
      settings: ctx.settings,
      vaultPath: ctx.vaultPath,
      command: ps,
      args: ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", script],
      cwd: root,
      env: {
        ZOOM_TASK_NAME: ctx.settings.taskName || "ZoomNotesSync",
      },
      timeoutMs: 2 * 60 * 1000,
      onLine: ctx.onLine,
    });
  }

  // Fallback: schtasks every 30 minutes
  const name = sanitizeJobName(ctx.settings.taskName);
  const tr = `powershell.exe -NoProfile -ExecutionPolicy Bypass -File "${runPs1}"`;
  return runProcess({
    kind: "register-task",
    settings: ctx.settings,
    vaultPath: ctx.vaultPath,
    command: "schtasks",
    args: [
      "/Create",
      "/F",
      "/TN",
      name,
      "/SC",
      "MINUTE",
      "/MO",
      "30",
      "/TR",
      tr,
      "/RL",
      "LIMITED",
    ],
    cwd: root,
    timeoutMs: 2 * 60 * 1000,
    onLine: ctx.onLine,
  });
}

async function registerDarwin(
  ctx: ScheduleContext,
  runSh: string
): Promise<RunResult> {
  const name = sanitizeJobName(ctx.settings.taskName);
  const label = `com.zoom-mynotes-sync.${name}`;
  const agentsDir = path.join(homeDir(), "Library", "LaunchAgents");
  fs.mkdirSync(agentsDir, { recursive: true });
  const plistPath = path.join(agentsDir, `${label}.plist`);
  const root = resolveSyncRoot(ctx.settings);
  const logOut = path.join(root, "logs", "launchd-stdout.log");
  const logErr = path.join(root, "logs", "launchd-stderr.log");
  fs.mkdirSync(path.join(root, "logs"), { recursive: true });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${escapeXml(runSh)}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${escapeXml(root)}</string>
  <key>StartInterval</key>
  <integer>1800</integer>
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>${escapeXml(logOut)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logErr)}</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
  fs.writeFileSync(plistPath, plist, "utf8");

  // unload if present, then load
  await runProcess({
    kind: "register-task",
    settings: ctx.settings,
    vaultPath: ctx.vaultPath,
    command: "launchctl",
    args: ["unload", plistPath],
    cwd: root,
    timeoutMs: 30_000,
    onLine: ctx.onLine,
  }).catch(() => undefined);

  return runProcess({
    kind: "register-task",
    settings: ctx.settings,
    vaultPath: ctx.vaultPath,
    command: "launchctl",
    args: ["load", plistPath],
    cwd: root,
    timeoutMs: 30_000,
    onLine: ctx.onLine,
  });
}

async function registerLinux(
  ctx: ScheduleContext,
  runSh: string
): Promise<RunResult> {
  const root = resolveSyncRoot(ctx.settings);
  const name = sanitizeJobName(ctx.settings.taskName);
  const begin = `${CRON_BEGIN} ${name}`;
  const end = `${CRON_END} ${name}`;
  const line = `*/30 * * * * /bin/bash ${shellQuotePosix(runSh)} >> ${shellQuotePosix(
    path.join(root, "logs", "cron-sync.log")
  )} 2>&1`;

  fs.mkdirSync(path.join(root, "logs"), { recursive: true });

  // Read existing crontab (empty is fine)
  let existing = "";
  try {
    const r = await runProcess({
      kind: "custom",
      settings: ctx.settings,
      vaultPath: ctx.vaultPath,
      command: "crontab",
      args: ["-l"],
      cwd: root,
      timeoutMs: 15_000,
      onLine: ctx.onLine,
    });
    if (r.code === 0) existing = r.stdout || "";
  } catch {
    existing = "";
  }

  const stripped = stripCronBlock(existing, begin, end);
  const next =
    (stripped.trimEnd() ? stripped.trimEnd() + "\n" : "") +
    `${begin}\n${line}\n${end}\n`;

  const tmp = path.join(root, ".zoom-mynotes-crontab.tmp");
  fs.writeFileSync(tmp, next, "utf8");

  try {
    const r = await runProcess({
      kind: "register-task",
      settings: ctx.settings,
      vaultPath: ctx.vaultPath,
      command: "crontab",
      args: [tmp],
      cwd: root,
      timeoutMs: 15_000,
      onLine: ctx.onLine,
    });
    return r;
  } finally {
    try {
      fs.unlinkSync(tmp);
    } catch {
      /* ignore */
    }
  }
}

function stripCronBlock(src: string, begin: string, end: string): string {
  const lines = src.split(/\r?\n/);
  const out: string[] = [];
  let skipping = false;
  for (const line of lines) {
    if (line.trim() === begin) {
      skipping = true;
      continue;
    }
    if (line.trim() === end) {
      skipping = false;
      continue;
    }
    if (!skipping) out.push(line);
  }
  // drop trailing empty lines noise
  while (out.length && out[out.length - 1] === "") out.pop();
  return out.join("\n") + (out.length ? "\n" : "");
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function runRegisterSchedule(
  ctx: ScheduleContext
): Promise<{ result: RunResult; detail: string }> {
  const files = writeLocalEnvFiles(ctx.settings, ctx.vaultPath);
  const platform = hostPlatform();
  const label = schedulerLabel();

  if (platform === "win32") {
    const result = await registerWindows(ctx, files.runPs1);
    return {
      result,
      detail:
        result.code === 0
          ? `${label} job '${sanitizeJobName(ctx.settings.taskName)}' every 30 min`
          : `Failed to register ${label}`,
    };
  }

  if (platform === "darwin") {
    const result = await registerDarwin(ctx, files.runSh);
    return {
      result,
      detail:
        result.code === 0
          ? `${label}: com.zoom-mynotes-sync.${sanitizeJobName(
              ctx.settings.taskName
            )} every 30 min`
          : `Failed to load LaunchAgent`,
    };
  }

  if (platform === "linux") {
    const result = await registerLinux(ctx, files.runSh);
    return {
      result,
      detail:
        result.code === 0
          ? `${label} entry every 30 min (user crontab)`
          : `Failed to install crontab entry (is cron available?)`,
    };
  }

  return {
    result: {
      kind: "register-task",
      code: 0,
      signal: null,
      stdout: "",
      stderr: "",
      durationMs: 0,
      command: "(skip)",
    },
    detail: `Background scheduling not automated on ${process.platform}. Use Obsidian auto-sync or run ${files.runSh} manually.`,
  };
}
